# Generated by Django 4.1.5 on 2023-05-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration', models.CharField(default='', max_length=50)),
                ('vin_number', models.CharField(max_length=17)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('number_etched_into_windows', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('agent_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pass_word', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
    ]
