# Generated by Django 4.2.1 on 2023-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentvehicle',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
